name: Pass variable between jobs

on:
  push:
    branches:
      - main

jobs:
  set-variable:
    runs-on: ubuntu-latest
    outputs:
      my_var: ${{ steps.set_output.outputs.my_var }}        
    steps:
      - name: Set a variable
        id: set_output
        run: echo "my_var=Hello, World!" >> $GITHUB_ENV

  use-variable:
    needs: set-variable
    runs-on: ubuntu-latest
    steps:
      - name: Access the variable from previous job
        run: |
          echo "Outputs: ${{ toJson(needs.set-variable.outputs) }}"
          echo "The value of my_var is: ${{ env.my_var }}"
