name: Pass variable between jobs

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    if: (needs.job1.outputs.output1 == 'hello')
    needs: job1
    steps:
      - name: test
        run: |
          echo ${{needs.job1.outputs.output1}}
      - name: dir-check
        run: |
          ls -al ${{ github.workspace }}
          echo "test" > /tmp/testfile.txt
          echo -e "\033[33mThis is a warning message\033[0m"  # Yellow for warning
          echo -e "\033[31mOperation failed\033[0m"  # Red for failure
          cat /tmp/testfile.txt
