name: Pass variable between jobs

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    if: (needs.job1.outputs.output1 == 'world')
    needs: job1
    steps:
      - name: test
        run: |
          echo ${{needs.job1.outputs.output1}}
      - name: dir-check
        run: |
          echo ${{ github.workspace }}
          ls -al ${{ github.workspace }}
          echo "test" > ${{ github.workspace }}/testfile.txt
          cat ${{ github.workspace }}/testfile.txt
