name: 'DB Migration'

on:
  #push:
  #  branches: [ "feat/dbmigration_action" ]
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Azure subscription environment name
        options:
        - test
        - stg  

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: DB Migrate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    container:
      image: mcr.microsoft.com/azure-cli
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: test
      run: |
        echo ${{ vars.ENVNAME }}
